apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearwake-api
  labels:
    app: clearwake-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clearwake-api
  template:
    metadata:
      labels:
        app: clearwake-api
    spec:
      containers:
        - name: api
          image: ghcr.io/tues-2026-pbl-11-klas/bees_project_2:68a5dacdaba321b94c33c3918c76e8d93ba0f709
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: clearwake-config
            - secretRef:
                name: clearwake-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/zones/
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/v1/zones/
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
