apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clearwake-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager
  target:
    name: clearwake-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: clearwake/mongodb-uri
